### PR TITLE
Added timeout to close connection

### PR DESCRIPTION
**Pull request by devmetal**
Hi, i wrote some modifications with full respect to the code style, i hope so :)
So i prefer the close connections because i want to avoid awkward situations with my development team.

I also added yarn.lock file and fixed the chai.config deprecation warning.

Firstly i added close and connect methods to log method, but in the benchmarks it was very slow compared to the original. After i decided to use timeout to close connection as you can see.

The final benchmarks with this:
messages count 46234
logging with close after timeout x 10,041 ops/sec ±3.81% (76 runs sampled)

(the original was x 13,691 ops/sec ±0.63% (82 runs sampled))

Thank you! :)

### CODE REVIEW

**Comment by devmetal** [comment]
Anybody here to maintain this module? Or my pr is not acceptable?

**Comment by cthayer** [comment]
@devmetal thanks for submitting this pull request.  I will review it and let you know

**Comment by cthayer** [comment]
@devmetal you did match the coding style nicely.  Thanks!

A couple notes:

1) I think using a timeout to disconnect should be optional with the default behavior being to preserve the original behavior of relying on winston to close the connection.  My thoughts on how to do that would be to set the default timeout to 0 and not use a timer when it's set to 0.

However, I'm not sure a timeout is best for managing the connection state.  Perhaps using `process.on('exit')` (or other process events) would be better than a timeout?  That way we get the same performance in message sending, but close the connection cleanly when the process exits.

If we do use a timeout to close the connection:

2) I think the timeout should be unreferenced so it does not keep the process open unnecessarily (my thought is that if the connection does not close it will keep the process open until the timeout is called and if the connection is not open then the process does not have to wait for our timeout before it exits)

3) I think there should be a way for the connection to be re-opened after our timeout has disconnected it.  Perhaps a check when sending the message to see if we need to call `connect()` before sending?




Unrelated to the above, I noticed that the benchmark script is using ecmascript 6 features (let, const, arrow functions).  Since this module is functional back to version 0.8.x of node is it possible to not use these features in that script?  (normally I wouldn't care, I love the new features, but this module is used in older versions and it would be nice if they could use the benchmark script too)

**Comment by devmetal** [comment]
Okay, i will do this modifications. Thank you :)

**Comment by devmetal** [comment]
I think, there are some problem with the old 0.8 version of nodejs. Like it can not handle correctly the timeouts. If you want to support that version, then i think my solution is not acceptable.

Edited

**Comment by devmetal** [comment]
Okay i modified my unit test to avoid setTimeout in tests

**Comment by devmetal** [comment]
Sorry i have to close this pull request and i open another one. This is not the correct way to handle this

**Pull request closed without merging**
