### PR TITLE
UDP6 suppport (Logstash 5.0)

### PR DESCRIPTION
**Pull request by RidgeA**
While I tried to set up logstash 5.0 and used your module to put logs from nodejs services to logstash I found that logstahs listens udp6 socket. I failed to set up logstash to listen udp4 socket, so I decided to make some improvement of your module.

### CODE REVIEW

**Comment by RidgeA** [comment]
I removed console.log (sorry : -) ), but all tests pass successfully on my PC 

image

**Comment by cthayer** [comment]
Thanks for this.

I think the default host should be `127.0.0.1` or `::1` depending on the value of `udpType`.

Also, for the travis test failures, the new travis containers don't support ipv6 so we have to use the old travis containers by setting `sudo: true` in the travis config.

**Comment by RidgeA** [comment]
Hello @cthayer .
I changed default host according to your comment.
As for travis configuration I added `sudo: true` into config file, but it doesn't help to pass the tests.
I didn't find any solution to enable IPv6 into travis container.

**Comment by devmetal** [comment]
@RidgeA  

Hi i checked the documentation and not the true is the valid option. Try set to required.

https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

Also i will be happy the ipv6 for logstash.

**Comment by RidgeA** [comment]
@devmetal It didn't help (
You can use my fork from https://github.com/RidgeA/winston-logstash-udp in your project.
I'm using it more than a month without issues.
Localy all test pass.

**Comment by cthayer** [comment]
@RidgeA @devmetal I'm going to merge this and then disable the ipv6 checks in travis since it does not seem to support it.

It will be in the next release.

**Comment by cthayer** [comment]
@RidgeA version 0.2.1 has been released with your changes

**Comment by RidgeA** [comment]
@cthayer thanks!

**Pull request merged**
