### PR TITLE
Yarn and unref socket

### PR DESCRIPTION
**Pull request by devmetal**
I added yarn.lock and fixed the chai deprecation warning.

Also i checked in the nodejs documentation, the socket has unref method like timeout. So i reverted some stuffs, and added just few lines.

It will solve the hangig socket issue

### CODE REVIEW

**Comment by devmetal** [comment]
Hi, what do you think about this pr?

**Comment by devmetal** [comment]
Guys, somebody can review my pr?

**Comment by cthayer** [comment]
@devmetal this looks good.  I will merge this for the next release.

Solves #10 for node version > 0.8

**Comment by cthayer** [comment]
@devmetal version 0.2.1 has been released with your changes

**Pull request merged**
